"""add spec_id to product_images

Revision ID: 872ffc62f4fd
Revises: c0a601baebed
Create Date: 2026-06-15 16:40:03.232308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872ffc62f4fd'
down_revision: Union[str, Sequence[str], None] = 'c0a601baebed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('spec_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_images_spec_id'), 'product_images', ['spec_id'], unique=False)
    op.create_foreign_key(None, 'product_images', 'product_specs', ['spec_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.drop_index(op.f('ix_product_images_spec_id'), table_name='product_images')
    op.drop_column('product_images', 'spec_id')
    # ### end Alembic commands ###
